#!/bin/bash


cd /home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/src/Green-Iteration-Routines

DOMAIN=20
MINDEPTH=3
SINGSUBT=1

INPUTFILE='../src/utilities/molecularConfigurations/hydrogenMoleculeAuxiliary.csv'
 

SRCDIR='/home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/src/'
VTKFILEDIR='None'


GRADIENTFREE='True'
SYMMETRICITERATION='False' 
GPUPRESENT='True'

TREECODE='False'
TREECODEORDER=0    
THETA=0.0
MAXPARNODE=8000  
BATCHSIZE=8000
BASE=1.0


GAUSSIANALPHA=1.0
 
#MESHTYPE='ParentChildrenIntegral'
MESHTYPE='LW5' 
GAUGESHIFT=-0.5


MIXINGPARAMETER=0.2 
MIXINGHISTORY=20 
 
INTRASCFTOLERANCE=3e-5
INTERSCFTOLERANCE=1e-6 
   
MIXING='Anderson'    
CELLORDER=4 
 
ADDITIONALDEPTHATATOMS=0 
RESTART='False'	 
#SAVEDMESH='ParentChildrenIntegral_500.0_1000000.0_1e-06_0.0.npy' 
#SAVEDMESH='ParentChildrenIntegral_500.0_1000000.0_1e-06_0.0_domain30.npy'
#SAVEDMESH='ParentChildrenIntegral_500.0_1000000.0_3e-06_0.0.npy'
#SAVEDMESH='ParentChildrenIntegral_500.0_1000000.0_3e-07_0.0.npy'
SAVEDMESH='None' 

for SMOOTHINGEPS in 0.0
do
for MAXDEPTH in 20  
do								  					 
for MESHPARAM4 in 500       
do
	for MESHPARAM3 in 3e-6 
	 
	do     
		for MESHPARAM2 in 1e6     
		do       
			for MESHPARAM1 in 500
			      
			do 
			#OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/paperData/hydrogenMolecule/meshparam_${MESHPARAM3}.csv"
			OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/andersonGI/meshparam_${MESHPARAM1}.csv"
						
			python -u testBatchGreenIterations_FixedPoint_noTree.py 	$DOMAIN $MINDEPTH $MAXDEPTH $ADDITIONALDEPTHATATOMS $CELLORDER $SINGSUBT \
																		$SMOOTHINGEPS $GAUSSIANALPHA $GAUGESHIFT $MESHTYPE $MESHPARAM1 $MESHPARAM2 $INTERSCFTOLERANCE $INTRASCFTOLERANCE \
																		$OUTPUTFILE $INPUTFILE $SRCDIR $VTKFILEDIR $GRADIENTFREE $SYMMETRICITERATION $MIXING $MIXINGPARAMETER $MIXINGHISTORY \
																		$GPUPRESENT $TREECODE $TREECODEORDER $THETA $MAXPARNODE $BATCHSIZE $MESHPARAM3 $MESHPARAM4 $BASE $RESTART $SAVEDMESH
			done
		done
	done
done
done
done		   
		