#!/bin/bash


cd /home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/src/Green-Iteration-Routines

DOMAIN=20
MINDEPTH=3
SINGSUBT=1

#INPUTFILE='../src/utilities/molecularConfigurations/benzeneAuxiliary.csv'


INPUTFILE='../src/utilities/molecularConfigurations/carbonMonoxideAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/oxygenAtomAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/O2Auxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/carbonAtomAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/berylliumAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/lithiumAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/hydrogenMoleculeAuxiliary.csv'

VTKFILEDIR='None'
SRCDIR='/home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/src/'


GRADIENTFREE='True'
SYMMETRICITERATION='False'
GPUPRESENT='True'
 
TREECODE='True'      
THETA=0.8  
MAXPARNODE=5000
BATCHSIZE=5000


GAUSSIANALPHA=1.0

MESHTYPE='ParentChildrenIntegral'
#MESHTYPE='LW5'
RESTART='False'	
SAVEDMESH='CO_PCI_3e-7.npy' 
#SAVEDMESH='None' 

ADDITIONALDEPTHATATOMS=0

MIXINGPARAMETER=0.5
MIXINGHISTORY=30 
   
INTRASCFTOLERANCE=1e-7
INTERSCFTOLERANCE=1e-6
    
MIXING='Anderson'    
SMOOTHINGEPS=0.0
GAUGESHIFT=-0.5

MESHPARAM3=3e-7
MESHPARAM2=1e6
for SINGSUBT in 1
do
for CELLORDER in 5
do	  
for BASE in 1  
do 
for MAXDEPTH in 20    
do								  					    
for MESHPARAM4 in 0 
do
	for TREECODEORDER in 10  
	#for TREECODEORDER in 0  
	do      
		for THETA in 0.5 0.6 0.7 0.8 
		#for THETA in 0.0 
		do   
			for MESHPARAM1 in 0	 	    
			do
			
			#OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/paperData/CarbonMonoxideData/treecodeApproxError_sizecheck_titan/CO_onlyFirst_treecode_tc${TREECODE}_tcOrder_${TREECODEORDER}_tcTheta_${THETA}_CellOrder_${CELLORDER}_PCI_${MESHPARAM3}.csv"
			OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/paperData/CarbonMonoxideData/treecodeApproxError/tc${TREECODE}_tcOrder_${TREECODEORDER}_tcTheta_${THETA}_CellOrder_${CELLORDER}_PCI_${MESHPARAM3}.csv"
			#OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/andersonGI/CO_onlyFirst_treecode_tc${TREECODE}_tcOrder_${TREECODEORDER}_tcTheta_${THETA}_CellOrder_${CELLORDER}_PCI_${MESHPARAM3}.csv"
			python -u testBatchGreenIterations_FixedPoint_noTree.py 	$DOMAIN $MINDEPTH $MAXDEPTH $ADDITIONALDEPTHATATOMS $CELLORDER $SINGSUBT \
																		$SMOOTHINGEPS $GAUSSIANALPHA $GAUGESHIFT $MESHTYPE $MESHPARAM1 $MESHPARAM2 $INTERSCFTOLERANCE $INTRASCFTOLERANCE \
																		$OUTPUTFILE $INPUTFILE $SRCDIR $VTKFILEDIR $GRADIENTFREE $SYMMETRICITERATION $MIXING $MIXINGPARAMETER $MIXINGHISTORY \
																		$GPUPRESENT $TREECODE $TREECODEORDER $THETA $MAXPARNODE $BATCHSIZE $MESHPARAM3 $MESHPARAM4 $BASE $RESTART $SAVEDMESH
			done   
		done
	done    
	
done  
done
done 
done    
done
