#!/bin/bash



cd /home/njvaughn/TAGI/3D-GreenIterations/src/Green-Iteration-Routines
DOMAIN=12
SINGSUBT=1

SRCDIR='/home/njvaughn/TAGI/3D-GreenIterations/src/'

#COREREPRESENTATION="AllElectron"
#INPUTFILE='molecularConfigurations/berylliumAuxiliary.csv'
#INPUTFILE='molecularConfigurations/hydrogenMoleculeAuxiliary.csv'
#INPUTFILE='molecularConfigurations/N2Auxiliary.csv'
#INPUTFILE='molecularConfigurations/NAuxiliary.csv'


COREREPRESENTATION="Pseudopotential"
INPUTFILE='molecularConfigurations/berylliumAuxiliaryPSP.csv'
#INPUTFILE='molecularConfigurations/N2AuxiliaryPSP.csv'
  

VTKFILEDIR='None'
 

GRADIENTFREE='True'
SYMMETRICITERATION='False'
GPUPRESENT='False'
 
TREECODE='True'      
MAXPARNODE=500
BATCHSIZE=500   
 
 
GAUSSIANALPHA=1.0 
GAUGESHIFT=-0.5
 
MESHTYPE='ParentChildrenIntegral'  
#MESHTYPE='LW5'
RESTART='False' 
SAVEDMESH='None'

ADDITIONALDEPTHATATOMS=0
GRADIENTFREE='True' 

MIXINGPARAMETER=0.5
MIXINGHISTORY=10  
  
INITIAL_GI_TOLERANCE=1e-3 
FINAL_GI_TOLERANCE=3e-5
GRADUALSTEPS=4
SCF_TOLERANCE=1e-4
     


MAXSIDELENGTH=6


MESHTYPE='PiecewiseUniform' 
MESHPARAM1=2.0 # near field spacing
MESHPARAM2=1.0 # near field cutoff

MESHPARAM3=3.0 # mid field spacing
MESHPARAM4=2.0 # mid field cutoff

APPROXIMATIONNAME=lagrange
 
for SINGULARITYHANDLING in subtraction 
do
for CELLORDER in 4
do                                                       
for TREECODEORDER in 7
do         
    for THETA in 0.7
    do   
        for MIXING in 'Anderson'            
        do 

        OUTPUTFILE="/home/njvaughn/ONCV-testing/N_mesh_${MESHPARAM3}_TC_${TREECODEORDER}_${THETA}.csv"
        
        srun -n $1 python -u TAGI-main.py     $DOMAIN $MAXSIDELENGTH $CELLORDER $SINGSUBT \
                                                $GAUSSIANALPHA $GAUGESHIFT $MESHTYPE $MESHPARAM1 $MESHPARAM2 $SCF_TOLERANCE \
                                                $INITIAL_GI_TOLERANCE $FINAL_GI_TOLERANCE $GRADUALSTEPS \
                                                $OUTPUTFILE $INPUTFILE $COREREPRESENTATION $SRCDIR $VTKFILEDIR $GRADIENTFREE $SYMMETRICITERATION $MIXING $MIXINGPARAMETER $MIXINGHISTORY \
                                                $GPUPRESENT $TREECODE $TREECODEORDER $THETA $MAXPARNODE $BATCHSIZE $MESHPARAM3 $MESHPARAM4 $RESTART $SAVEDMESH \
                                                $SINGULARITYHANDLING $APPROXIMATIONNAME
        done   
    done 
done      
done
done
