#!/bin/bash


cd /Users/nathanvaughn/Documents/GitHub/TAGI/3D-GreenIterations/src/Green-Iteration-Routines
SINGSUBT=1 
GPUPRESENT='False'  
SRCDIR='/Users/nathanvaughn/Documents/GitHub/TAGI/3D-GreenIterations/src/'


#COREREPRESENTATION="AllElectron"
#INPUTFILE='molecularConfigurations/berylliumAuxiliary.csv' 
#INPUTFILE='molecularConfigurations/hydrogenMoleculeAuxiliary.csv'
#INPUTFILE='molecularConfigurations/N2Auxiliary.csv'
#INPUTFILE='molecularConfigurations/NAuxiliary.csv'

COREREPRESENTATION="Pseudopotential"
#INPUTFILE='molecularConfigurations/testingAuxiliaryPSP.csv'
#INPUTFILE='molecularConfigurations/C20AuxiliaryPSP.csv'
#INPUTFILE='molecularConfigurations/Si2AuxiliaryPSP.csv'
#INPUTFILE='molecularConfigurations/siliconAuxiliaryPSP.csv'
INPUTFILE='molecularConfigurations/berylliumAuxiliaryPSP.csv'
#INPUTFILE='molecularConfigurations/TiO2AuxiliaryPSP.csv'
#INPUTFILE='molecularConfigurations/carbonAuxiliaryPSP.csv'
#INPUTFILE='molecularConfigurations/N2AuxiliaryPSP.csv'
  

VTKFILEDIR='/Users/nathanvaughn/Desktop/'
 

GRADIENTFREE='True'
SYMMETRICITERATION='False'
 
TREECODE='True'      
 
 
GAUGESHIFT=-0.5
MIXING='Anderson'
 
#MESHTYPE='LW5'
RESTART='False' 
SAVEDMESH='None'

ADDITIONALDEPTHATATOMS=0
GRADIENTFREE='True' 

MIXINGPARAMETER=0.5
MIXINGHISTORY=10  
     
INITIAL_GI_TOLERANCE=3e-2 
FINAL_GI_TOLERANCE=3e-5
GRADUALSTEPS=10
SCF_TOLERANCE=3e-2
     



APPROXIMATIONNAME=hermite
SINGULARITYHANDLING=subtraction

REGULARIZE='False'
EPSILON=0.0
   
GAUSSIANALPHA=2.0 
TREECODEORDER=4
THETA=0.8

CELLORDER=4
FINEORDER=4


 
MESHTYPE='coarsenedUniformTwoLevel'

DOMAIN=16
MAXSIDELENGTH=8
MESHPARAM1=1.0 # near field spacing 
MESHPARAM2=8.0 # far field spacing
MESHPARAM3=2.0 # ball radius

  
TWOMESHSTART=999
#GIFORM="Simultaneous"
GIFORM="Sequential"
#GIFORM="Greedy" 

for MESHPARAM4 in -2
do                                                         
    for BATCHSIZE in 20
    do        
        for MAXPARNODE in 200
        do   

        OUTPUTFILE="/Users/nathanvaughn/Documents/ONCV-testing/beryllium/twoMesh/twoMesh_correction_at_end_${APPROXIMATIONNAME}_${TREECODEORDER}_theta_${THETA}_leafsize_${MAXPARNODE}_batchsize_${BATCHSIZE}.csv" 
        mpirun -n $1 python -u TAGI-main.py     $DOMAIN $MAXSIDELENGTH $CELLORDER $FINEORDER $SINGSUBT \
                                                $GAUSSIANALPHA $GAUGESHIFT $MESHTYPE $MESHPARAM1 $MESHPARAM2 $SCF_TOLERANCE \
                                                $INITIAL_GI_TOLERANCE $FINAL_GI_TOLERANCE $GRADUALSTEPS \
                                                $OUTPUTFILE $INPUTFILE $COREREPRESENTATION $SRCDIR $VTKFILEDIR $GRADIENTFREE $SYMMETRICITERATION $MIXING $MIXINGPARAMETER $MIXINGHISTORY \
                                                $GPUPRESENT $TREECODE $TREECODEORDER $THETA $MAXPARNODE $BATCHSIZE $MESHPARAM3 $MESHPARAM4 $RESTART $SAVEDMESH \
                                                $SINGULARITYHANDLING $APPROXIMATIONNAME $REGULARIZE $EPSILON $TWOMESHSTART $GIFORM
        done 
    done      
done
       