#!/bin/bash



cd /home/njvaughn/TAGI/3D-GreenIterations/src/Green-Iteration-Routines
DOMAIN=20
SINGSUBT=1

SRCDIR='/home/njvaughn/TAGI/3D-GreenIterations/src/'

#COREREPRESENTATION="AllElectron"
#INPUTFILE='molecularConfigurations/berylliumAuxiliary.csv'
#INPUTFILE='molecularConfigurations/hydrogenMoleculeAuxiliary.csv'
#INPUTFILE='molecularConfigurations/N2Auxiliary.csv'
#INPUTFILE='molecularConfigurations/NAuxiliary.csv'


COREREPRESENTATION="Pseudopotential"
INPUTFILE='molecularConfigurations/berylliumAuxiliaryPSP.csv'
#INPUTFILE='molecularConfigurations/N2AuxiliaryPSP.csv'
  

VTKFILEDIR='/Users/nathanvaughn/Desktop/'
 

GRADIENTFREE='True'
SYMMETRICITERATION='False'
GPUPRESENT='True'
 
TREECODE='True'      
MAXPARNODE=4000
BATCHSIZE=4000   
 
 
GAUSSIANALPHA=1.0 
GAUGESHIFT=-0.5
 
MESHTYPE='ParentChildrenIntegral'  
#MESHTYPE='LW5'
RESTART='False' 
SAVEDMESH='None'

ADDITIONALDEPTHATATOMS=0
GRADIENTFREE='True' 

MIXINGPARAMETER=0.5
MIXINGHISTORY=10  
  
INITIAL_GI_TOLERANCE=1e-3 
FINAL_GI_TOLERANCE=1e-5
GRADUALSTEPS=4
SCF_TOLERANCE=5e-5
     


MESHTYPE='coarsenedUniform'
MAXSIDELENGTH=8 
MESHPARAM1=0.5 # near field spacing 
MESHPARAM2=8.0 # far field spacing
MESHPARAM3=2.0 # ball radius
MESHPARAM4=0.0 # unused


#MAXSIDELENGTH=6
#MESHPARAM1=0.375 # near field spacing 
#MESHPARAM2=6.0 # far field spacing
#MESHPARAM3=1.5 # ball radius
#MESHPARAM4=0.0 # unused


#MAXSIDELENGTH=8
#MESHPARAM1=0.25 # near field spacing 
#MESHPARAM2=4.0 # far field spacing
#MESHPARAM3=2.0 # ball radius
#MESHPARAM4=0.0 # unused



APPROXIMATIONNAME=lagrange
 
for SINGULARITYHANDLING in subtraction 
do
for CELLORDER in 5
do                                                       
for TREECODEORDER in 8
do         
    for THETA in 0.5
    do   
        for MIXING in 'Anderson'            
        do 

        OUTPUTFILE="/home/njvaughn/ONCV-testing/N_mesh_${MESHPARAM3}_TC_${TREECODEORDER}_${THETA}.csv"
        
        mpirun --mca btl_openib_allow_ib true --mca plm_rsh_no_tree_spawn true -n 1 python -u TAGI-main.py     $DOMAIN $MAXSIDELENGTH $CELLORDER $SINGSUBT \
                                                $GAUSSIANALPHA $GAUGESHIFT $MESHTYPE $MESHPARAM1 $MESHPARAM2 $SCF_TOLERANCE \
                                                $INITIAL_GI_TOLERANCE $FINAL_GI_TOLERANCE $GRADUALSTEPS \
                                                $OUTPUTFILE $INPUTFILE $COREREPRESENTATION $SRCDIR $VTKFILEDIR $GRADIENTFREE $SYMMETRICITERATION $MIXING $MIXINGPARAMETER $MIXINGHISTORY \
                                                $GPUPRESENT $TREECODE $TREECODEORDER $THETA $MAXPARNODE $BATCHSIZE $MESHPARAM3 $MESHPARAM4 $RESTART $SAVEDMESH \
                                                $SINGULARITYHANDLING $APPROXIMATIONNAME
        done   
    done 
done      
done
done
