#!/bin/bash
#SBATCH --job-name="gl-testing"
#SBATCH --output="dataFiles/two-mesh-domain16-order5-%j.%N.out"
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=20
#SBATCH --gres=gpu:1
#SBATCH --mem-per-cpu=2gb
#SBATCH -t 01:00:00
#SBATCH --no-requeue
#SBATCH -A krasny1




cd /home/njvaughn/TAGI/3D-GreenIterations/src/Green-Iteration-Routines
SINGSUBT=1

SRCDIR='/home/njvaughn/TAGI/3D-GreenIterations/src/'


#SBATCH --constraint=exclusive



#COREREPRESENTATION="AllElectron"
#INPUTFILE='molecularConfigurations/berylliumAuxiliary.csv' 
#INPUTFILE='molecularConfigurations/hydrogenMoleculeAuxiliary.csv'
#INPUTFILE='molecularConfigurations/N2Auxiliary.csv'
#INPUTFILE='molecularConfigurations/NAuxiliary.csv'


COREREPRESENTATION="Pseudopotential"
INPUTFILE='molecularConfigurations/TiO2AuxiliaryPSP.csv'


VTKFILEDIR='/Users/nathanvaughn/Desktop/'
 

GRADIENTFREE='True'
SYMMETRICITERATION='False'
GPUPRESENT='True'
 
TREECODE='True'      
MAXPARNODE=4000
BATCHSIZE=4000   
 
 
GAUGESHIFT=-0.5
MIXING='Anderson'
 
#MESHTYPE='LW5'
RESTART='False' 
SAVEDMESH='None'

ADDITIONALDEPTHATATOMS=0
GRADIENTFREE='True' 

MIXINGPARAMETER=0.5
MIXINGHISTORY=10  
  
INITIAL_GI_TOLERANCE=1e-3
FINAL_GI_TOLERANCE=3e-7
GRADUALSTEPS=5
SCF_TOLERANCE=2e-6
     


MESHTYPE='coarsenedUniform'

MAXSIDELENGTH=8
MESHPARAM1=0.5 # near field spacing 
MESHPARAM2=8.0 # far field spacing
MESHPARAM3=2.0 # ball radius


APPROXIMATIONNAME=lagrange
SINGULARITYHANDLING=subtraction

REGULARIZE='False'
EPSILON=0.0

GAUSSIANALPHA=2.0 
TREECODEORDER=7
THETA=0.7


MESHPARAM4=0
for DOMAIN in 32
do                                                         
    for CELLORDER in 4
    do         
        for FINEORDER in 4
        do  
         
        OUTPUTFILE="/home/njvaughn/ONCV-testing/TiO2/testing/mesh_${MESHPARAM1}_${MESHPARAM2}_${MESHPARAM3}_${MESHPARAM4}_order_${CELLORDER}_fineOrder_${FINEORDER}.csv" 
        srun -n 1 python -u TAGI-main.py     $DOMAIN $MAXSIDELENGTH $CELLORDER $FINEORDER $SINGSUBT \
                                                $GAUSSIANALPHA $GAUGESHIFT $MESHTYPE $MESHPARAM1 $MESHPARAM2 $SCF_TOLERANCE \
                                                $INITIAL_GI_TOLERANCE $FINAL_GI_TOLERANCE $GRADUALSTEPS \
                                                $OUTPUTFILE $INPUTFILE $COREREPRESENTATION $SRCDIR $VTKFILEDIR $GRADIENTFREE $SYMMETRICITERATION $MIXING $MIXINGPARAMETER $MIXINGHISTORY \
                                                $GPUPRESENT $TREECODE $TREECODEORDER $THETA $MAXPARNODE $BATCHSIZE $MESHPARAM3 $MESHPARAM4 $RESTART $SAVEDMESH \
                                                $SINGULARITYHANDLING $APPROXIMATIONNAME $REGULARIZE $EPSILON
        done 
    done      
done