#!/bin/bash
#SBATCH --job-name="comet-testing"
#SBATCH --output="dataFiles/treecode_params-%j.%N.out"
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gres=gpu:2
#SBATCH --mem=80GB 
#SBATCH -t 00:20:00
#SBATCH --no-requeue
#SBATCH -A krasny1

## For comet
##SBATCH --constraint=exclusive
#export LD_LIBRARY_PATH=/home/njvaughn/mvapich2_ib_Zoltan_Shared/lib:$LD_LIBRARY_PATH
 

cd /home/njvaughn/TAGI/3D-GreenIterations/src/Green-Iteration-Routines
SINGSUBT=1 
GPUPRESENT='True'  
 
SRCDIR='/home/njvaughn/TAGI/3D-GreenIterations/src/' 

#COREREPRESENTATION="AllElectron" 
#INPUTFILE='molecularConfigurations/berylliumAuxiliary.csv' 
#INPUTFILE='molecularConfigurations/hydrogenMoleculeAuxiliary.csv'
#INPUTFILE='molecularConfigurations/N2Auxiliary.csv'
#INPUTFILE='molecularConfigurations/NAuxiliary.csv'

COREREPRESENTATION="Pseudopotential"
#INPUTFILE='molecularConfigurations/testingAuxiliaryPSP.csv' 
#INPUTFILE='molecularConfigurations/C20AuxiliaryPSP.csv'
INPUTFILE='molecularConfigurations/Si2AuxiliaryPSP.csv'
#INPUTFILE='molecularConfigurations/siliconAuxiliaryPSP.csv'
#INPUTFILE='molecularConfigurations/berylliumAuxiliaryPSP.csv'
#INPUTFILE='molecularConfigurations/TiO2AuxiliaryPSP.csv'
#INPUTFILE='molecularConfigurations/carbonAuxiliaryPSP.csv'
#INPUTFILE='molecularConfigurations/N2AuxiliaryPSP.csv' 
  

VTKFILEDIR='/Users/nathanvaughn/Desktop/'
 

GRADIENTFREE='True'
SYMMETRICITERATION='False'
 
TREECODE='True'      
 
 
GAUGESHIFT=-0.5
MIXING='Anderson'
 
#MESHTYPE='LW5'
RESTART='False' 
SAVEDMESH='None' 

ADDITIONALDEPTHATATOMS=0
GRADIENTFREE='True' 

MIXINGPARAMETER=0.5 
MIXINGHISTORY=10  
  

INITIAL_GI_TOLERANCE=3e-2 
FINAL_GI_TOLERANCE=1e-5 
GRADUALSTEPS=8
SCF_TOLERANCE=3e-5



APPROXIMATIONNAME=hermite
SINGULARITYHANDLING=subtraction

REGULARIZE='False'
EPSILON=0.0
   
GAUSSIANALPHA=2.0 


CELLORDER=4
FINEORDER=4


 
MESHTYPE='coarsenedUniformTwoLevel'

DOMAIN=32
MAXSIDELENGTH=8
MESHPARAM1=0.5 # near field spacing  
MESHPARAM2=8.0 # far field spacing
MESHPARAM3=2.0 # ball radius

  
TWOMESHSTART=999
#GIFORM="Simultaneous"
GIFORM="Sequential" 
#GIFORM="Greedy" 
MESHPARAM4=-2

APPROXIMATIONNAME=hermite 
BATCHSIZE=2000
MAXPARNODE=2000

   
for THETA in 0.8
do                                                          
    for TREECODEORDER in 4
    do        

        OUTPUTFILE="/home/njvaughn/ONCV-testing/Si2/treecodeParams/lagrange_not_tighteningTCparams__${APPROXIMATIONNAME}_theta_${THETA}_TCorder_${TREECODEORDER}.csv" 

        #ibrun -n 4 python -u TAGI-main.py     $DOMAIN $MAXSIDELENGTH $CELLORDER $FINEORDER $SINGSUBT \
        mpirun -n 1 python -u TAGI-main.py     $DOMAIN $MAXSIDELENGTH $CELLORDER $FINEORDER $SINGSUBT \
                                                $GAUSSIANALPHA $GAUGESHIFT $MESHTYPE $MESHPARAM1 $MESHPARAM2 $SCF_TOLERANCE \
                                                $INITIAL_GI_TOLERANCE $FINAL_GI_TOLERANCE $GRADUALSTEPS \
                                                $OUTPUTFILE $INPUTFILE $COREREPRESENTATION $SRCDIR $VTKFILEDIR $GRADIENTFREE $SYMMETRICITERATION $MIXING $MIXINGPARAMETER $MIXINGHISTORY \
                                                $GPUPRESENT $TREECODE $TREECODEORDER $THETA $MAXPARNODE $BATCHSIZE $MESHPARAM3 $MESHPARAM4 $RESTART $SAVEDMESH \
                                                $SINGULARITYHANDLING $APPROXIMATIONNAME $REGULARIZE $EPSILON $TWOMESHSTART $GIFORM
    done      
done