#!/bin/bash
#SBATCH --job-name="gl-testing"
#SBATCH --output="dataFiles/sizeCheck_lagrange_one_SCF_hermite_vs_lagrange_testing_%j.%N.out"
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=48gb  
#SBATCH -t 12:00:00
#SBATCH --no-requeue
#SBATCH -A krasny1
 

cd /home/njvaughn/TAGI/3D-GreenIterations/src/Green-Iteration-Routines
SINGSUBT=1 
GPUPRESENT='True'  
 
SRCDIR='/home/njvaughn/TAGI/3D-GreenIterations/src/' 

#COREREPRESENTATION="AllElectron" 
#INPUTFILE='molecularConfigurations/berylliumAuxiliary.csv' 
#INPUTFILE='molecularConfigurations/hydrogenMoleculeAuxiliary.csv'
#INPUTFILE='molecularConfigurations/N2Auxiliary.csv'
#INPUTFILE='molecularConfigurations/NAuxiliary.csv'

COREREPRESENTATION="Pseudopotential"
#INPUTFILE='molecularConfigurations/testingAuxiliaryPSP.csv' 
#INPUTFILE='molecularConfigurations/C20AuxiliaryPSP.csv'
INPUTFILE='molecularConfigurations/Si2AuxiliaryPSP.csv'
#INPUTFILE='molecularConfigurations/siliconAuxiliaryPSP.csv'
#INPUTFILE='molecularConfigurations/berylliumAuxiliaryPSP.csv'
#INPUTFILE='molecularConfigurations/TiO2AuxiliaryPSP.csv'
#INPUTFILE='molecularConfigurations/carbonAuxiliaryPSP.csv'
#INPUTFILE='molecularConfigurations/N2AuxiliaryPSP.csv' 
  

VTKFILEDIR='/Users/nathanvaughn/Desktop/'
 

GRADIENTFREE='True'
SYMMETRICITERATION='False'
 
TREECODE='True'      
 
 
GAUGESHIFT=-0.5
MIXING='Anderson'
 
#MESHTYPE='LW5'
RESTART='False' 
SAVEDMESH='None' 

ADDITIONALDEPTHATATOMS=0
GRADIENTFREE='True' 

MIXINGPARAMETER=0.5 
MIXINGHISTORY=10  
  
 
INITIAL_GI_TOLERANCE=3e-3 
FINAL_GI_TOLERANCE=1e-5 
GRADUALSTEPS=8
SCF_TOLERANCE=3e0



APPROXIMATIONNAME=hermite
SINGULARITYHANDLING=subtraction 

REGULARIZE='False'
EPSILON=0.0
   
GAUSSIANALPHA=2.0 

    
CELLORDER=4 
FINEORDER=4


 
MESHTYPE='coarsenedUniformTwoLevel'

DOMAIN=32
MAXSIDELENGTH=8
MESHPARAM1=0.25 # near field spacing  
MESHPARAM2=8.0 # far field spacing
MESHPARAM3=2.0 # ball radius

  
TWOMESHSTART=999
#GIFORM="Simultaneous"
GIFORM="Sequential" 
#GIFORM="Greedy" 
MESHPARAM4=-2
 
 
 
APPROXIMATIONNAME=hermite 
BATCHSIZE=4000
CLUSTERSIZE=4000

TREECODEORDER=5
   
for THETA in 0.5 0.7 0.9
do                                                          
    #CLUSTERSIZE=${BATCHSIZE}

    OUTPUTFILE="/home/njvaughn/ONCV-testing/Si2/treecodeParams_fine/first_SCF_${APPROXIMATIONNAME}_theta_${THETA}_TCorder_${TREECODEORDER}_batchSize_${BATCHSIZE}_clusterSize_${CLUSTERSIZE}.csv" 
    #OUTPUTFILE="/home/njvaughn/ONCV-testing/Si2/treecodeParams_fine/first_SCF_DirectSum.csv" 

    mpirun --mca btl_openib_allow_ib true --mca plm_rsh_no_tree_spawn true -n 1 python -u TAGI-main.py     $DOMAIN $MAXSIDELENGTH $CELLORDER $FINEORDER $SINGSUBT \
                                            $GAUSSIANALPHA $GAUGESHIFT $MESHTYPE $MESHPARAM1 $MESHPARAM2 $SCF_TOLERANCE \
                                            $INITIAL_GI_TOLERANCE $FINAL_GI_TOLERANCE $GRADUALSTEPS \
                                            $OUTPUTFILE $INPUTFILE $COREREPRESENTATION $SRCDIR $VTKFILEDIR $GRADIENTFREE $SYMMETRICITERATION $MIXING $MIXINGPARAMETER $MIXINGHISTORY \
                                            $GPUPRESENT $TREECODE $TREECODEORDER $THETA $CLUSTERSIZE $BATCHSIZE $MESHPARAM3 $MESHPARAM4 $RESTART $SAVEDMESH \
                                            $SINGULARITYHANDLING $APPROXIMATIONNAME $REGULARIZE $EPSILON $TWOMESHSTART $GIFORM
done