#!/bin/bash
#SBATCH --job-name="gl-testing"
#SBATCH --output="dataFiles/lagrange_param_sweep-%j.%N.out"
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=48gb  
#SBATCH -t 00:20:00
#SBATCH --no-requeue   
#SBATCH -A krasny1
 

mpirun --mca btl_openib_allow_ib true --mca plm_rsh_no_tree_spawn true -n 1 python -u testPseudopotentialMesh.py
