#!/bin/bash


cd /home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/KohnShamTests


DOMAIN=30
MINDEPTH=4
SINGSUBT=1

INPUTFILE='../src/utilities/molecularConfigurations/benzeneAuxiliary.csv'


#INPUTFILE='../src/utilities/molecularConfigurations/carbonMonoxideAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/oxygenAtomAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/carbonAtomAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/berylliumAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/lithiumAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/hydrogenMoleculeAuxiliary.csv'

VTKFILEDIR='/home/njvaughn/O_with_anderson/LW5_1500o5_plots_eigRes'


GRADIENTFREE='True'
GPUPRESENT='True'

TREECODE='False'
TREECODEORDER=0
THETA=0.0
MAXPARNODE=8000
BATCHSIZE=8000
BASE=1.0


GAUSSIANALPHA=1.0

MESHTYPE='LW5'


MIXINGPARAMETER=0.5   
 
INTRASCFTOLERANCE=5e-5  
INTERSCFTOLERANCE=1e-6 
   
MIXING='Anderson'    
CELLORDER=4
 
DEPTHATATOMS=2 
	 

for SMOOTHINGEPS in 0.0
do
for MAXDEPTH in 20 
do								  					 
for MESHPARAM4 in 0
do
	for MESHPARAM3 in 0
	do   
		for MESHPARAM2 in 0
		do 
			for MESHPARAM1 in 500
			    
			do
			OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/benzeneTests/ds_cellOrder${CELLORDER}_smoothingEps${SMOOTHINGEPS}_maxDepth${MAXDEPTH}_minDepth${MINDEPTH}_${MESHPARAM1}_${MESHPARAM2}_${MESHPARAM3}_${MESHPARAM4}.csv"
			python -u testBatchGreenIterations_KS.py 	$DOMAIN $MINDEPTH $MAXDEPTH $DEPTHATATOMS $CELLORDER $SINGSUBT \
																		$SMOOTHINGEPS $GAUSSIANALPHA $MESHTYPE $MESHPARAM1 $MESHPARAM2 $INTERSCFTOLERANCE $INTRASCFTOLERANCE \
																		$OUTPUTFILE $INPUTFILE $VTKFILEDIR $GRADIENTFREE $MIXING $MIXINGPARAMETER \
																		$GPUPRESENT $TREECODE $TREECODEORDER $THETA $MAXPARNODE $BATCHSIZE $MESHPARAM3 $MESHPARAM4 $BASE 
			done
		done
	done
done
done
done		  
		