#!/bin/bash


cd /home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/KohnShamTests

DOMAIN=20
MINDEPTH=3
SINGSUBT=1

#INPUTFILE='../src/utilities/molecularConfigurations/benzeneAuxiliary.csv'


#INPUTFILE='../src/utilities/molecularConfigurations/carbonMonoxideAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/oxygenAtomAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/O2Auxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/carbonAtomAuxiliary.csv'
INPUTFILE='../src/utilities/molecularConfigurations/berylliumAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/lithiumAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/hydrogenMoleculeAuxiliary.csv'

VTKFILEDIR='None'

 
GRADIENTFREE='True'
SYMMETRICITERATION='False'
GPUPRESENT='True'
 
TREECODE='False'      
THETA=0.8  
MAXPARNODE=8000
BATCHSIZE=8000


GAUSSIANALPHA=1.0
GAUGESHIFT=-0.5

#MESHTYPE='ParentChildrenIntegral'
MESHTYPE='LW5'
RESTART='False'	
#SAVEDMESH='CO_PCI_3e-7.npy' 
SAVEDMESH='None' 

ADDITIONALDEPTHATATOMS=0

MIXINGPARAMETER=0.5 
MIXINGHISTORY=10 
  
INTRASCFTOLERANCE=5e-7
INTERSCFTOLERANCE=5e-6
    
MIXING='Anderson'    
SMOOTHINGEPS=0.0

MESHPARAM3=3e-7
MESHPARAM2=1e6
for SINGSUBT in 1 
do
for CELLORDER in 5
do	    
for BASE in 1 
do 
for MAXDEPTH in 20    
do								  					    
for MESHPARAM4 in 0  
do 
	for TREECODEORDER in 0 
	do      
		for THETA in 0.0  
		do  
			for MIXING in 'Anderson' 'Simple' 'None'		    
			do

			OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/paperData/density-mixing/Be_mixing_$MIXING.csv"
			 
			python -u testBatchGreenIterations_FixedPoint.py 	$DOMAIN $MINDEPTH $MAXDEPTH $ADDITIONALDEPTHATATOMS $CELLORDER $SINGSUBT \
																		$SMOOTHINGEPS $GAUSSIANALPHA $GAUGESHIFT $MESHTYPE $MESHPARAM1 $MESHPARAM2 $INTERSCFTOLERANCE $INTRASCFTOLERANCE \
																		$OUTPUTFILE $INPUTFILE $VTKFILEDIR $GRADIENTFREE $SYMMETRICITERATION $MIXING $MIXINGPARAMETER $MIXINGHISTORY \
																		$GPUPRESENT $TREECODE $TREECODEORDER $THETA $MAXPARNODE $BATCHSIZE $MESHPARAM3 $MESHPARAM4 $BASE $RESTART $SAVEDMESH
			done   
		done 
	done     
	
done  
done
done 
done    
done
