#!/bin/bash
cd /home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/KohnShamTests


DOMAIN=20
MAXDEPTH=20
MINDEPTH=3
SINGSUBT=1
SMOOTHINGN=0
SMOOTHINGEPS=0

INPUTFILE='../src/utilities/molecularConfigurations/carbonMonoxideAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/oxygenAtomAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/carbonAtomAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/berylliumAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/lithiumAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/hydrogenMoleculeAuxiliary.csv'


GRADIENTFREE='False'


ORDER=4
MESHTYPE='LW5'
MESHPARAM=500


MIXINGPARAMETER=0.5

INTRASCFTOLERANCE=1e-6
INTERSCFTOLERANCE=1e-6


MIXING='Anderson'	


#OUTPUTFILE='/home/njvaughn/CO_with_anderson/LW5_1000o4_MGS.csv'
#VTKFILEDIR='/home/njvaughn/CO_with_anderson/LW5_1000o4_plots_MGS'
OUTPUTFILE='/home/njvaughn/O_with_anderson/LW3_1000o4_gradientFree.csv'
VTKFILEDIR='/home/njvaughn/CO_with_anderson/LW3_1000o4_gradientFree_plots'
python -u testBatchGreenIterations_KS.py $DOMAIN $MINDEPTH $MAXDEPTH $ORDER $SINGSUBT \
	$SMOOTHINGN $SMOOTHINGEPS $MESHTYPE $MESHPARAM $INTERSCFTOLERANCE $INTRASCFTOLERANCE \
	$OUTPUTFILE $INPUTFILE $VTKFILEDIR $GRADIENTFREE $MIXING $MIXINGPARAMETER