#!/bin/bash
cd /home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/KohnShamTests


DOMAIN=20
MAXDEPTH=20
MINDEPTH=3
SINGSUBT=0
SMOOTHINGN=0
SMOOTHINGEPS=0

#INPUTFILE='../src/utilities/molecularConfigurations/carbonMonoxideAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/oxygenAtomAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/carbonAtomAuxiliary.csv'
INPUTFILE='../src/utilities/molecularConfigurations/berylliumAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/lithiumAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/hydrogenMoleculeAuxiliary.csv'



GRADIENTFREE='True'


ORDER=4
MESHTYPE='LW5'
MESHPARAM=500

MIXINGPARAMETER=0.5

INTRASCFTOLERANCE=1e-2
INTERSCFTOLERANCE=1e-6

MIXING='Anderson'	

OUTPUTFILE='/home/njvaughn/CO_with_anderson/testing.csv'
VTKFILEDIR='/home/njvaughn/CO_with_anderson/LW5_1500o5_plots_eigRes'
python -u testBatchGreenIterations_KS.py $DOMAIN $MINDEPTH $MAXDEPTH $ORDER $SINGSUBT \
	$SMOOTHINGN $SMOOTHINGEPS $MESHTYPE $MESHPARAM $INTERSCFTOLERANCE $INTRASCFTOLERANCE \
	$OUTPUTFILE $INPUTFILE $VTKFILEDIR $GRADIENTFREE $MIXING $MIXINGPARAMETER
	
	
	