#!/bin/bash


cd /home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/src/Green-Iteration-Routines
#cd /Users/nathanvaughn/Documents/GitHub/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/src/Green-Iteration-Routines

DOMAIN=20
MINDEPTH=3
SINGSUBT=1

SRCDIR='/home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/src/'
#SRCDIR='/Users/nathanvaughn/Documents/GitHub/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/src/'
#INPUTFILE='utilities/molecularConfigurations/berylliumAuxiliary.csv'
INPUTFILE='utilities/molecularConfigurations/hydrogenMoleculeAuxiliary.csv'

VTKFILEDIR='None'


GRADIENTFREE='True'
SYMMETRICITERATION='False'
GPUPRESENT='False'
 
TREECODE='True'      
MAXPARNODE=2000
BATCHSIZE=2000   
 
 
GAUSSIANALPHA=1.0 
GAUGESHIFT=-0.5

#MESHTYPE='ParentChildrenIntegral'
MESHTYPE='LW5'
RESTART='False'	
SAVEDMESH='None'

ADDITIONALDEPTHATATOMS=0

MIXINGPARAMETER=0.5
MIXINGHISTORY=10 
  
INITIAL_GI_TOLERANCE=1e-3  
FINAL_GI_TOLERANCE=3e-5
GRADUALSTEPS=4
SCF_TOLERANCE=1e-4
     
SMOOTHINGEPS=0.0    

MESHPARAM1=500
MESHPARAM2=0
MESHPARAM4=0
MESHPARAM3=1e-3
BASE=1  

NUMDEVICES=0
NUMTHREADS=1 

for SINGSUBT in 1
do
for CELLORDER in 2 
do	      
for MESHPARAM1 in 50
do   
for MAXDEPTH in 4     
do								  	 				     
for GRADIENTFREE in 'True'    
do  
	for TREECODEORDER in 8   
	do         
		for THETA in 0.1
		do   
			for MIXING in 'Anderson'		    
			do 

			OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/GreatLakes/TAGI/H2_mesh_${MESHPARAM3}_TC_${TREECODEORDER}_${THETA}.csv"
			#OUTPUTFILE="/Users/nathanvaughn/Documents/synchronizedDataFiles/mpi-testing/Be_mesh_${MESHPARAM3}_TC_${TREECODEORDER}_${THETA}.csv"
			
			mpirun -n $1 python -u testBatchGreenIterations_mpi.py 	$DOMAIN $MINDEPTH $MAXDEPTH $ADDITIONALDEPTHATATOMS $CELLORDER $SINGSUBT \
																		$SMOOTHINGEPS $GAUSSIANALPHA $GAUGESHIFT $MESHTYPE $MESHPARAM1 $MESHPARAM2 $SCF_TOLERANCE \
																		$INITIAL_GI_TOLERANCE $FINAL_GI_TOLERANCE $GRADUALSTEPS \
																		$OUTPUTFILE $INPUTFILE $SRCDIR $VTKFILEDIR $GRADIENTFREE $SYMMETRICITERATION $MIXING $MIXINGPARAMETER $MIXINGHISTORY \
																		$GPUPRESENT $TREECODE $TREECODEORDER $THETA $MAXPARNODE $BATCHSIZE $MESHPARAM3 $MESHPARAM4 $BASE $RESTART $SAVEDMESH \
																		$NUMDEVICES $NUMTHREADS
			done   
		done 
	done      
	
done      
done
done 
done    
done
