#!/bin/bash


cd /home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/src/Green-Iteration-Routines

DOMAIN=30
MINDEPTH=3
SINGSUBT=1

SRCDIR='/home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/src/'
INPUTFILE='utilities/molecularConfigurations/benzeneAuxiliary.csv'

VTKFILEDIR='None'


GRADIENTFREE='True'
SYMMETRICITERATION='False'
GPUPRESENT='True'
 
TREECODE='True'      
MAXPARNODE=5000
BATCHSIZE=5000


GAUSSIANALPHA=1.0
GAUGESHIFT=-0.5

MESHTYPE='ParentChildrenIntegral'
#MESHTYPE='LW5'
RESTART='False'	
SAVEDMESH='benzene_3e-7.npy' 
#SAVEDMESH='None' 
  
ADDITIONALDEPTHATATOMS=0

MIXINGPARAMETER=0.2 
MIXINGHISTORY=6
  
INTRASCFTOLERANCE=1e-7
INTERSCFTOLERANCE=1e-5
     
MIXING='Anderson'    
SMOOTHINGEPS=0.0

MESHPARAM1=500
MESHPARAM2=0
MESHPARAM4=0   

for SINGSUBT in 1 
do
for CELLORDER in 5 
do	      
for BASE in 1 
do   
for MAXDEPTH in 20    
do								  	 				     
for GRADIENTFREE in 'True'    
do  
	for TREECODEORDER in 8
	do         
		for THETA in 0.7 
		do  
			for MESHPARAM3 in 3e-7  
			do
			OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/paperData/best-times/tight_Benzene_mesh_${CELLORDER}_${MESHPARAM3}_TC_${TREECODEORDER}_${THETA}.csv"

			#OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/noTreeTesting/benzene_async_tcOrder_${TREECODEORDER}_tcTheta_${THETA}_meshParam3_${MESHPARAM3}.csv"			
			python -u testBatchGreenIterations_FixedPoint_noTree.py 	$DOMAIN $MINDEPTH $MAXDEPTH $ADDITIONALDEPTHATATOMS $CELLORDER $SINGSUBT \
																		$SMOOTHINGEPS $GAUSSIANALPHA $GAUGESHIFT $MESHTYPE $MESHPARAM1 $MESHPARAM2 $INTERSCFTOLERANCE $INTRASCFTOLERANCE \
																		$OUTPUTFILE $INPUTFILE $SRCDIR $VTKFILEDIR $GRADIENTFREE $SYMMETRICITERATION $MIXING $MIXINGPARAMETER $MIXINGHISTORY \
																		$GPUPRESENT $TREECODE $TREECODEORDER $THETA $MAXPARNODE $BATCHSIZE $MESHPARAM3 $MESHPARAM4 $BASE $RESTART $SAVEDMESH
			done   
		done 
	done     
	
done      
done
done 
done    
done
