#!/bin/bash


cd /home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/src/Green-Iteration-Routines

DOMAIN=20
MINDEPTH=3
SINGSUBT=1
SRCDIR='/home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/src/'


#INPUTFILE='../src/utilities/molecularConfigurations/oxygenAtomAuxiliary.csv'
INPUTFILE='utilities/molecularConfigurations/carbonMonoxideAuxiliary.csv' 

VTKFILEDIR='None'


SYMMETRICITERATION='False'
GPUPRESENT='True'
 
TREECODE='True'      
THETA=0.8  
MAXPARNODE=5000
BATCHSIZE=5000


GAUSSIANALPHA=1.0
GAUGESHIFT=-0.5

#MESHTYPE='ParentChildrenIntegral'
MESHTYPE='LW5'
RESTART='False'	
#SAVEDMESH='CO_PCI_3e-7.npy' 
SAVEDMESH='None' 

ADDITIONALDEPTHATATOMS=0

MIXINGPARAMETER=0.4 
MIXINGHISTORY=20 
  
INTRASCFTOLERANCE=1e-7
INTERSCFTOLERANCE=3e-6
     
MIXING='Anderson'    
SMOOTHINGEPS=0.0

MESHPARAM1=1000
MESHPARAM2=0
MESHPARAM4=0

for SINGSUBT in 1 
do
for CELLORDER in 4
do	      
for BASE in 1 
do  
for MAXDEPTH in 20    
do								  					    
for GRADIENTFREE in 'Laplacian' 'False' 'True'    
do  
	for TREECODEORDER in 7
	do        
		for THETA in 0.7 
		do  
			for MESHPARAM3 in 3e-5 3e-6 3e-7 3e-8    
			do

			#OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/paperData/OxygenData/gradientFree_redo/meshParam_${MESHPARAM3}_gradientFree_${GRADIENTFREE}_mixingParameter_${MIXINGPARAMETER}.csv"
			OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/paperData/CarbonMonoxideData/gradientFree/meshParam_${MESHPARAM3}_gradientFree_${GRADIENTFREE}_mixingParameter_${MIXINGPARAMETER}.csv"
			
			#python -u testBatchGreenIterations_FixedPoint_noTree.py 	$DOMAIN $MINDEPTH $MAXDEPTH $ADDITIONALDEPTHATATOMS $CELLORDER $SINGSUBT \
			python -u testBatchGreenIterations_FixedPoint.py 	$DOMAIN $MINDEPTH $MAXDEPTH $ADDITIONALDEPTHATATOMS $CELLORDER $SINGSUBT \
																		$SMOOTHINGEPS $GAUSSIANALPHA $GAUGESHIFT $MESHTYPE $MESHPARAM1 $MESHPARAM2 $INTERSCFTOLERANCE $INTRASCFTOLERANCE \
																		$OUTPUTFILE $INPUTFILE $SRCDIR $VTKFILEDIR $GRADIENTFREE $SYMMETRICITERATION $MIXING $MIXINGPARAMETER $MIXINGHISTORY \
																		$GPUPRESENT $TREECODE $TREECODEORDER $THETA $MAXPARNODE $BATCHSIZE $MESHPARAM3 $MESHPARAM4 $BASE $RESTART $SAVEDMESH
																		

			done   
		done 
	done     
	
done     
done
done 
done    
done
