#!/bin/bash


cd /home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/KohnShamTests

DOMAIN=20
MINDEPTH=3
SINGSUBT=1


INPUTFILE='../src/utilities/molecularConfigurations/berylliumAuxiliary.csv'

VTKFILEDIR='None'


GRADIENTFREE='True'
SYMMETRICITERATION='False'
GPUPRESENT='True'
 
TREECODE='False'      
THETA=0.8  
MAXPARNODE=8000
BATCHSIZE=8000


GAUSSIANALPHA=1.0
GAUGESHIFT=-0.5

MESHTYPE='ParentChildrenIntegral'
RESTART='False'	
SAVEDMESH='None' 

ADDITIONALDEPTHATATOMS=0

MIXINGPARAMETER=0.5 
MIXINGHISTORY=20 
  
INTRASCFTOLERANCE=1e-8
INTERSCFTOLERANCE=1e-6
     
MIXING='Anderson'    
SMOOTHINGEPS=0.0

MESHPARAM1=0
MESHPARAM2=0
MESHPARAM4=0

for SINGSUBT in 1 
do
for CELLORDER in 5
do	      
for BASE in 1 
do   
for MAXDEPTH in 20    
do								  	 				    
for GRADIENTFREE in 'True'    
do  
	for TREECODEORDER in 0
	do        
		for THETA in 0.0  
		do  
			for MESHPARAM3 in 3e-6 1e-6 3e-7    
			#for MESHPARAM3 in 3e-5 1e-5 2e-6 8e-8 1e-7    
			do

			OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/paperData/hRefinement/Be_meshParam_${MESHPARAM3}_cellOrder_${CELLORDER}.csv"
			
			python -u testBatchGreenIterations_FixedPoint.py 	$DOMAIN $MINDEPTH $MAXDEPTH $ADDITIONALDEPTHATATOMS $CELLORDER $SINGSUBT \
																		$SMOOTHINGEPS $GAUSSIANALPHA $GAUGESHIFT $MESHTYPE $MESHPARAM1 $MESHPARAM2 $INTERSCFTOLERANCE $INTRASCFTOLERANCE \
																		$OUTPUTFILE $INPUTFILE $VTKFILEDIR $GRADIENTFREE $SYMMETRICITERATION $MIXING $MIXINGPARAMETER $MIXINGHISTORY \
																		$GPUPRESENT $TREECODE $TREECODEORDER $THETA $MAXPARNODE $BATCHSIZE $MESHPARAM3 $MESHPARAM4 $BASE $RESTART $SAVEDMESH
			done   
		done 
	done     
	
done     
done
done 
done    
done
