#!/bin/bash


cd /home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/src/Green-Iteration-Routines

DOMAIN=30
MINDEPTH=3
SINGSUBT=1

SRCDIR='/home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/src/'
#INPUTFILE='utilities/molecularConfigurations/berylliumAuxiliary.csv'
#INPUTFILE='utilities/molecularConfigurations/oxygenAtomAuxiliary.csv'
#INPUTFILE='utilities/molecularConfigurations/carbonMonoxideAuxiliary.csv' 
INPUTFILE='utilities/molecularConfigurations/benzeneAuxiliary.csv'

VTKFILEDIR='None'


GRADIENTFREE='True'
SYMMETRICITERATION='False'
GPUPRESENT='True'
 
TREECODE='True'      
MAXPARNODE=16000
BATCHSIZE=16000


GAUSSIANALPHA=1.0
GAUGESHIFT=-0.5

MESHTYPE='ParentChildrenIntegral'
#MESHTYPE='LW5'
RESTART='False'	
SAVEDMESH='None' 

ADDITIONALDEPTHATATOMS=0

MIXINGPARAMETER=0.5 
MIXINGHISTORY=20 
  
INTRASCFTOLERANCE=5e-5
INTERSCFTOLERANCE=5e-6
     
MIXING='Anderson'    
SMOOTHINGEPS=0.0

MESHPARAM1=500
MESHPARAM2=0
MESHPARAM4=0   

for SINGSUBT in 1 
do
for CELLORDER in 5 
do	      
for BASE in 1 
do   
for MAXDEPTH in 20    
do								  	 				     
for GRADIENTFREE in 'True'    
do  
	for TREECODEORDER in 8
	do         
		for THETA in 0.7  
		do  
			for MESHPARAM3 in 1e-7  
			do

			#OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/noTreeTesting/Benzene_PCI_meshParam_${MESHPARAM3}.csv"
			OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/noTreeTesting/no_gp_phi_PCI_meshParam_${MESHPARAM3}.csv"
			
			#python -u testBatchGreenIterations_FixedPoint.py 	$DOMAIN $MINDEPTH $MAXDEPTH $ADDITIONALDEPTHATATOMS $CELLORDER $SINGSUBT \
			python -u testBatchGreenIterations_FixedPoint_noTree.py 	$DOMAIN $MINDEPTH $MAXDEPTH $ADDITIONALDEPTHATATOMS $CELLORDER $SINGSUBT \
																		$SMOOTHINGEPS $GAUSSIANALPHA $GAUGESHIFT $MESHTYPE $MESHPARAM1 $MESHPARAM2 $INTERSCFTOLERANCE $INTRASCFTOLERANCE \
																		$OUTPUTFILE $INPUTFILE $SRCDIR $VTKFILEDIR $GRADIENTFREE $SYMMETRICITERATION $MIXING $MIXINGPARAMETER $MIXINGHISTORY \
																		$GPUPRESENT $TREECODE $TREECODEORDER $THETA $MAXPARNODE $BATCHSIZE $MESHPARAM3 $MESHPARAM4 $BASE $RESTART $SAVEDMESH
			done   
		done 
	done     
	
done      
done
done 
done    
done
