#!/bin/bash


cd /home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/src/Green-Iteration-Routines

DOMAIN=20
MINDEPTH=3
SINGSUBT=1

SRCDIR='/home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/src/'
INPUTFILE='utilities/molecularConfigurations/berylliumAuxiliary.csv'

VTKFILEDIR='None'


GRADIENTFREE='True'
SYMMETRICITERATION='False'
GPUPRESENT='True'
 
TREECODE='True'      
MAXPARNODE=4000
BATCHSIZE=4000   
 
 
GAUSSIANALPHA=1.0 
GAUGESHIFT=-0.5

MESHTYPE='ParentChildrenIntegral'
RESTART='False'	
SAVEDMESH='None'

ADDITIONALDEPTHATATOMS=0

MIXINGPARAMETER=0.5
MIXINGHISTORY=10 
  
INITIAL_GI_TOLERANCE=1e-3  
FINAL_GI_TOLERANCE=3e-5
GRADUALSTEPS=2
SCF_TOLERANCE=1e-4
     
SMOOTHINGEPS=0.0    

MESHPARAM1=500
MESHPARAM2=0
MESHPARAM4=0
BASE=1  

NUMDEVICES=4
NUMTHREADS=4 

for SINGSUBT in 1
do
for CELLORDER in 4  
do	      
for MESHPARAM3 in 1e-5
do   
for MAXDEPTH in 20     
do								  	 				     
for GRADIENTFREE in 'True'    
do  
	for TREECODEORDER in 6   
	do         
		for THETA in 0.8
		do   
			for MIXING in 'Anderson'		    
			do 

			OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/paperData/best-times-updated/Be_mesh_${MESHPARAM3}_TC_${TREECODEORDER}_${THETA}.csv"
			
			python -u testBatchGreenIterations_FixedPoint_noTree.py 	$DOMAIN $MINDEPTH $MAXDEPTH $ADDITIONALDEPTHATATOMS $CELLORDER $SINGSUBT \
																		$SMOOTHINGEPS $GAUSSIANALPHA $GAUGESHIFT $MESHTYPE $MESHPARAM1 $MESHPARAM2 $SCF_TOLERANCE \
																		$INITIAL_GI_TOLERANCE $FINAL_GI_TOLERANCE $GRADUALSTEPS \
																		$OUTPUTFILE $INPUTFILE $SRCDIR $VTKFILEDIR $GRADIENTFREE $SYMMETRICITERATION $MIXING $MIXINGPARAMETER $MIXINGHISTORY \
																		$GPUPRESENT $TREECODE $TREECODEORDER $THETA $MAXPARNODE $BATCHSIZE $MESHPARAM3 $MESHPARAM4 $BASE $RESTART $SAVEDMESH \
																		$NUMDEVICES $NUMTHREADS
			done   
		done 
	done      
	
done      
done
done 
done    
done
