#!/bin/bash

cd /home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/tests
python testBatchGreenIterations.py 10 4 20 10000 5e-6
python testBatchGreenIterations.py 10 4 20 15000 5e-6
python testBatchGreenIterations.py 10 4 20 20000 5e-6
python testBatchGreenIterations.py 10 4 20 25000 5e-6
