#!/bin/bash
cd /home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/KohnShamTests


DOMAIN=20
MAXDEPTH=20
MINDEPTH=3
SINGSUBT=0
SMOOTHINGN=0
SMOOTHINGEPS=0
INTRASCFTOLERANCE=1e-4
INTERSCFTOLERANCE=1e-5

#INPUTFILE='../src/utilities/molecularConfigurations/carbonMonoxideAuxiliary.csv'
INPUTFILE='../src/utilities/molecularConfigurations/oxygenAtomAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/carbonAtomAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/berylliumAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/lithiumAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/hydrogenMoleculeAuxiliary.csv'


ORDER=3
MESHTYPE='LW5'	



MESHPARAM=1000
#OUTPUTFILE='/home/njvaughn/O_Gaussian/LW5_2000_noSmoothingVext.csv'
#OUTPUTFILE='/home/njvaughn/O_Gaussian/LW5_2000_manySCF_single_additional_refinement.csv'
OUTPUTFILE='/home/njvaughn/O_Gaussian/testing.csv'
python -u testBatchGreenIterations_KS.py $DOMAIN $MINDEPTH $MAXDEPTH $ORDER $SINGSUBT \
	$SMOOTHINGN $SMOOTHINGEPS $MESHTYPE $MESHPARAM $INTERSCFTOLERANCE $INTRASCFTOLERANCE \
	$OUTPUTFILE $INPUTFILE $VTKFILEDIR
	
