#!/bin/bash


cd /home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/src/Green-Iteration-Routines

DOMAIN=20
MINDEPTH=3
SINGSUBT=1

SRCDIR='/home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/src/'
#INPUTFILE='utilities/molecularConfigurations/berylliumAuxiliary.csv'
INPUTFILE='utilities/molecularConfigurations/carbonMonoxideAuxiliary.csv' 

VTKFILEDIR='None'


GRADIENTFREE='True'
SYMMETRICITERATION='False'
GPUPRESENT='True'
 
TREECODE='False'      
MAXPARNODE=4000
BATCHSIZE=4000


GAUSSIANALPHA=1.0
GAUGESHIFT=-0.5

#MESHTYPE='ParentChildrenIntegral'
MESHTYPE='LW5'
RESTART='False'	
SAVEDMESH='None' 

ADDITIONALDEPTHATATOMS=0

MIXINGPARAMETER=0.5 
MIXINGHISTORY=20 
  
INTRASCFTOLERANCE=1e-8
INTERSCFTOLERANCE=1e-6
     
MIXING='Anderson'    
SMOOTHINGEPS=0.0

MESHPARAM1=500
MESHPARAM2=0
MESHPARAM4=0

for SINGSUBT in 1 
do
for CELLORDER in 5 
do	      
for BASE in 1 
do   
for MAXDEPTH in 20    
do								  	 				    
for GRADIENTFREE in 'True'    
do  
	for TREECODEORDER in 8
	do        
		for THETA in 0.8  
		do  
			for MESHPARAM3 in 0  
			do

			OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/noTreeTesting/Be_meshParam_${MESHPARAM1}.csv"
			
			#python -u testBatchGreenIterations_FixedPoint.py 	$DOMAIN $MINDEPTH $MAXDEPTH $ADDITIONALDEPTHATATOMS $CELLORDER $SINGSUBT \
			python -u testBatchGreenIterations_FixedPoint_noTree.py 	$DOMAIN $MINDEPTH $MAXDEPTH $ADDITIONALDEPTHATATOMS $CELLORDER $SINGSUBT \
																		$SMOOTHINGEPS $GAUSSIANALPHA $GAUGESHIFT $MESHTYPE $MESHPARAM1 $MESHPARAM2 $INTERSCFTOLERANCE $INTRASCFTOLERANCE \
																		$OUTPUTFILE $INPUTFILE $SRCDIR $VTKFILEDIR $GRADIENTFREE $SYMMETRICITERATION $MIXING $MIXINGPARAMETER $MIXINGHISTORY \
																		$GPUPRESENT $TREECODE $TREECODEORDER $THETA $MAXPARNODE $BATCHSIZE $MESHPARAM3 $MESHPARAM4 $BASE $RESTART $SAVEDMESH
			done   
		done 
	done     
	
done     
done
done 
done    
done
