#!/bin/bash

cd /home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/tests
python testBatchGreenIterations.py 12 5 12 0.05 1e-5 5e-6
#python testBatchGreenIterations.py 8 4 15 0.05 5e-5 5e-6
#python testBatchGreenIterations.py 8 4 15 0.05 1e-5 5e-6


