#!/bin/bash


cd /home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/KohnShamTests


DOMAIN=30
MINDEPTH=3
SINGSUBT=1

INPUTFILE='../src/utilities/molecularConfigurations/benzeneAuxiliary.csv'


#INPUTFILE='../src/utilities/molecularConfigurations/carbonMonoxideAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/oxygenAtomAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/carbonAtomAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/berylliumAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/lithiumAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/hydrogenMoleculeAuxiliary.csv'

VTKFILEDIR='/home/njvaughn/O_with_anderson/LW5_1500o5_plots_eigRes'


GRADIENTFREE='True'
GPUPRESENT='True'

TREECODE='True'
TREECODEORDER=7
THETA=0.8
MAXPARNODE=8000
BATCHSIZE=8000
BASE=1.0


GAUSSIANALPHA=1.0

MESHTYPE='ParentChildrenIntegral'


MIXINGPARAMETER=0.75 
MIXINGHISTORY=10 
 
INTRASCFTOLERANCE=5e-5 
INTERSCFTOLERANCE=1e-6 
   
MIXING='Anderson'    
CELLORDER=5 
 
ADDITIONALDEPTHATATOMS=0 
RESTART='False'	 
SAVEDMESH=''

for SMOOTHINGEPS in 0.0
do
for MAXDEPTH in 20 
do								  					 
for MESHPARAM4 in 0   
do
	for MESHPARAM3 in 1e-2 
	do    
		for MESHPARAM2 in 1e6 
		do 
			for MESHPARAM1 in 1e6
			    
			do
			OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/benzeneTests/tc_gaugeShift0p5_mindepth3_tcOrder${TREECODEORDER}_theta${THETA}_PCI_${MESHPARAM3}_9random_mixingHistory${MIXINGHISTORY}.csv"
			python -u testBatchGreenIterations_KS.py 	$DOMAIN $MINDEPTH $MAXDEPTH $ADDITIONALDEPTHATATOMS $CELLORDER $SINGSUBT \
																		$SMOOTHINGEPS $GAUSSIANALPHA $MESHTYPE $MESHPARAM1 $MESHPARAM2 $INTERSCFTOLERANCE $INTRASCFTOLERANCE \
																		$OUTPUTFILE $INPUTFILE $VTKFILEDIR $GRADIENTFREE $MIXING $MIXINGPARAMETER $MIXINGHISTORY\
																		$GPUPRESENT $TREECODE $TREECODEORDER $THETA $MAXPARNODE $BATCHSIZE $MESHPARAM3 $MESHPARAM4 $BASE $RESTART $SAVEDMESH
			done
		done
	done
done
done
done		   
		