#!/bin/bash


cd /home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/src/Green-Iteration-Routines

DOMAIN=20
MINDEPTH=3
SINGSUBT=1

SRCDIR='/home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/src/'
#INPUTFILE='utilities/molecularConfigurations/hydrogenMoleculeAuxiliary.csv'
INPUTFILE='utilities/molecularConfigurations/berylliumAuxiliary.csv'
#INPUTFILE='utilities/molecularConfigurations/lithiumAuxiliary.csv'   
#INPUTFILE='utilities/molecularConfigurations/oxygenAtomAuxiliary.csv'
#INPUTFILE='utilities/molecularConfigurations/carbonMonoxideAuxiliary.csv' 
#INPUTFILE='utilities/molecularConfigurations/O2Auxiliary.csv' 
#INPUTFILE='utilities/molecularConfigurations/benzeneAuxiliary.csv'

VTKFILEDIR='None'


GRADIENTFREE='True'
SYMMETRICITERATION='False'
GPUPRESENT='True'
 
TREECODE='True'      
MAXPARNODE=4000
BATCHSIZE=4000   
 
 
GAUSSIANALPHA=1.0 
GAUGESHIFT=-0.5

MESHTYPE='ParentChildrenIntegral'
#MESHTYPE='LW5'
RESTART='False'	
#SAVEDMESH='Be_PCI_1e-3.npy' 
#SAVEDMESH='Benzene_1e-7.npy'
#SAVEDMESH='H2-best-mesh.npy'
#SAVEDMESH='CO-best-mesh.npy'
#SAVEDMESH='O2-3e-6.npy'
#SAVEDMESH='CO_3e-6.npy'
#SAVEDMESH='beryllium-3e-06.npy'
SAVEDMESH='None'

ADDITIONALDEPTHATATOMS=0

MIXINGPARAMETER=0.5
MIXINGHISTORY=10 
  
INITIAL_GI_TOLERANCE=1e-3  
FINAL_GI_TOLERANCE=1e-6
GRADUALSTEPS=3
SCF_TOLERANCE=1e-7
     
#MIXING='Anderson'     
SMOOTHINGEPS=0.0    

MESHPARAM1=500
MESHPARAM2=0
MESHPARAM4=0
BASE=1  

NUMDEVICES=4
NUMTHREADS=4 

for SINGSUBT in 1
do
for CELLORDER in 4  
do	      
for MESHPARAM3 in 3e-6
do   
for MAXDEPTH in 20     
do								  	 				     
for GRADIENTFREE in 'True'    
do  
	for TREECODEORDER in 8   
	do         
		for THETA in 0.6
		do   
			#for MIXING in 'Simple' 'Anderson' 'None'  	     
			for MIXING in 'Anderson'		    
			do 

			#OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/paperData/CarbonMonoxideData/mixing/CO_$MIXING.csv"
			#OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/paperData/CarbonMonoxideData/singsubt/CO_$SINGSUBT.csv"
			#OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/paperData/CarbonMonoxideData/forVisit/CO_${MESHPARAM3}.csv"

			OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/noTreeTesting/O2_gradual_meshParam_${MESHPARAM3}.csv"
			#OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/noTreeTesting/CO_init2_gradual_min10_meshParam_${MESHPARAM3}_mixing_${MIXINGPARAMETER}.csv"
			#OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/noTreeTesting/CO_gradual_min10_meshParam_${MESHPARAM3}_mixing_${MIXINGPARAMETER}.csv"
			#OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/noTreeTesting/CO_gradual_min10_meshParam_${MESHPARAM3}_mixing_${MIXINGPARAMETER}.csv"
			#OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/noTreeTesting/Benzene_testing_async_kernels.csv"
			#OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/noTreeTesting/Benzene_PCI_meshParam_${MESHPARAM3}.csv"
			#OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/noTreeTesting/no_gp_phi_PCI_meshParam_${MESHPARAM3}.csv"
			
			#python -u testBatchGreenIterations_FixedPoint.py 	$DOMAIN $MINDEPTH $MAXDEPTH $ADDITIONALDEPTHATATOMS $CELLORDER $SINGSUBT \
			python -u testBatchGreenIterations_FixedPoint_noTree.py 	$DOMAIN $MINDEPTH $MAXDEPTH $ADDITIONALDEPTHATATOMS $CELLORDER $SINGSUBT \
																		$SMOOTHINGEPS $GAUSSIANALPHA $GAUGESHIFT $MESHTYPE $MESHPARAM1 $MESHPARAM2 $SCF_TOLERANCE \
																		$INITIAL_GI_TOLERANCE $FINAL_GI_TOLERANCE $GRADUALSTEPS \
																		$OUTPUTFILE $INPUTFILE $SRCDIR $VTKFILEDIR $GRADIENTFREE $SYMMETRICITERATION $MIXING $MIXINGPARAMETER $MIXINGHISTORY \
																		$GPUPRESENT $TREECODE $TREECODEORDER $THETA $MAXPARNODE $BATCHSIZE $MESHPARAM3 $MESHPARAM4 $BASE $RESTART $SAVEDMESH \
																		$NUMDEVICES $NUMTHREADS
			done   
		done 
	done      
	
done      
done
done 
done    
done
