#!/bin/bash


cd /home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/KohnShamTests

DOMAIN=20
MINDEPTH=3
SINGSUBT=1

INPUTFILE='../src/utilities/molecularConfigurations/carbonMonoxideAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/oxygenAtomAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/carbonAtomAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/berylliumAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/lithiumAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/hydrogenMoleculeAuxiliary.csv'

VTKFILEDIR='/home/njvaughn/O_with_anderson/LW5_1500o5_plots_eigRes'


GRADIENTFREE='True'
GPUPRESENT='True'

TREECODE='True'


GAUSSIANALPHA=1.0

MESHTYPE='LW5'
MESHPARAM1=1500
MESHPARAM2=0
MESHPARAM3=0
MESHPARAM4=0

MIXINGPARAMETER=0.5   
 
INTRASCFTOLERANCE=1e-7  
INTERSCFTOLERANCE=5e-6 
   
MIXING='Anderson'    
CELLORDER=5
SMOOTHINGEPS=0.0

RESTART='False'

for ADDITIONALDEPTHATATOMS in 0
do
for CELLORDER in 5 
do	 
for BASE in 1
do
for MAXDEPTH in 20   
do								  					 
for TREECODEORDER in 7  
do 
	for THETA in 0.8
	do    
		for MAXPARNODE in 8000
		do 
			for BATCHSIZE in 8000 		    
			do
			OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/krasnyMeshTests/CO_treecode_testing/tc_tcOrder${TREECODEORDER}_theta${THETA}_maxparnode${MAXPARNODE}_batchsize${BATCHSIZE}.csv"
			python -u testBatchGreenIterations_KS.py 	$DOMAIN $MINDEPTH $MAXDEPTH $ADDITIONALDEPTHATATOMS $CELLORDER $SINGSUBT \
																		$SMOOTHINGEPS $GAUSSIANALPHA $MESHTYPE $MESHPARAM1 $MESHPARAM2 $INTERSCFTOLERANCE $INTRASCFTOLERANCE \
																		$OUTPUTFILE $INPUTFILE $VTKFILEDIR $GRADIENTFREE $MIXING $MIXINGPARAMETER \
																		$GPUPRESENT $TREECODE $TREECODEORDER $THETA $MAXPARNODE $BATCHSIZE $MESHPARAM3 $MESHPARAM4 $BASE $RESTART
			done
		done
	done 
	
done 
done
done
done
done