#!/bin/bash

cd /home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/tests


#python testBatchGreenIterations.py 12 3 14 0 1 1.0 LW3 100 1e-7 /home/njvaughn/results_CC_6_19/mid_to_cc.csv
#python testBatchGreenIterations.py 12 3 14 0 1 1.0 LW3 200 1e-7 /home/njvaughn/results_CC_6_19/mid_to_cc.csv
#python testBatchGreenIterations.py 12 3 14 0 1 1.0 LW3 400 1e-7 /home/njvaughn/results_CC_6_19/mid_to_cc.csv
#python testBatchGreenIterations.py 12 3 14 0 1 1.0 LW3 800 1e-7 /home/njvaughn/results_CC_6_19/mid_to_cc.csv
#python testBatchGreenIterations.py 12 3 14 0 1 1.0 LW3 1600 1e-7 /home/njvaughn/results_CC_6_19/mid_to_cc.csv
#python testBatchGreenIterations.py 12 3 14 0 1 1.0 LW3 3200 1e-7 /home/njvaughn/results_CC_6_19/mid_to_cc.csv


cd /home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/CC_tests

#python testBatchGreenIterations_CC.py 12 2 14 4 1 0 0.0 LW3   30 1e-8 /home/njvaughn/results_CC_6_19/mid_to_cc.csv
#python testBatchGreenIterations_CC.py 12 2 14 4 1 0 0.0 LW3   50 1e-8 /home/njvaughn/results_CC_6_19/mid_to_cc.csv
#python testBatchGreenIterations_CC.py 12 2 14 4 1 0 0.0 LW3  100 1e-8 /home/njvaughn/results_CC_6_19/mid_to_cc.csv
#python testBatchGreenIterations_CC.py 12 2 14 4 1 0 0.0 LW3  400 1e-8 /home/njvaughn/results_CC_6_19/mid_to_cc.csv

#python testBatchGreenIterations_CC.py 12 2 14 5 1 0 0.0 LW3   30 1e-8 /home/njvaughn/results_CC_6_19/mid_to_cc.csv
#python testBatchGreenIterations_CC.py 12 2 14 5 1 0 0.0 LW3   50 1e-8 /home/njvaughn/results_CC_6_19/mid_to_cc.csv
#python testBatchGreenIterations_CC.py 12 2 14 5 1 0 0.0 LW3  100 1e-8 /home/njvaughn/results_CC_6_19/mid_to_cc.csv
#python testBatchGreenIterations_CC.py 12 2 14 5 1 0 0.0 LW3  150 1e-8 /home/njvaughn/results_CC_6_19/mid_to_cc.csv
#python testBatchGreenIterations_CC.py 12 2 14 5 1 0 0.0 LW3  200 1e-8 /home/njvaughn/results_CC_6_19/mid_to_cc.csv

python testBatchGreenIterations_CC.py 12 2 14 5 1 0 0.0 LW1  150 1e-8 /home/njvaughn/results_CC_6_19/mid_to_cc.csv
python testBatchGreenIterations_CC.py 12 2 14 5 1 0 0.0 LW3  150 1e-8 /home/njvaughn/results_CC_6_19/mid_to_cc.csv


