#!/bin/bash


cd /home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/KohnShamTests

DOMAIN=20
MINDEPTH=3
SINGSUBT=1

INPUTFILE='../src/utilities/molecularConfigurations/carbonMonoxideAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/oxygenAtomAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/O2Auxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/carbonAtomAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/berylliumAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/lithiumAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/hydrogenMoleculeAuxiliary.csv'

VTKFILEDIR='/home/njvaughn/O_with_anderson/LW5_1500o5_plots_eigRes'


GRADIENTFREE='True'
SYMMETRICITERATION='False'
GPUPRESENT='True'
 
TREECODE='False'      
TREECODEORDER=8 
THETA=0.8  
MAXPARNODE=1000
BATCHSIZE=1000


GAUSSIANALPHA=1.0

#MESHTYPE='ParentChildrenIntegral'
MESHTYPE='LW5'
RESTART='False'	
#SAVEDMESH='CO_PCI_3e-7.npy' 
SAVEDMESH='None' 


MIXINGPARAMETER=0.5 
MIXINGHISTORY=40 
  
INTRASCFTOLERANCE=1e-10
INTERSCFTOLERANCE=1e-5 
    
MIXING='Anderson'    
SMOOTHINGEPS=0.0

MESHPARAM3=3e-7
MESHPARAM2=1e6

NORBITALS=3
TARGETENERGYEIGENVALUE=-10.88
 
for ADDITIONALDEPTHATATOMS in 0 
do
for CELLORDER in 5
do	    
for BASE in 1
do 
for MAXDEPTH in 20   
do								  					    
for MESHPARAM4 in 0 
do
	for TREECODEORDER in 0
	do     
		for GAUGESHIFT in -0.0
		do 
			for MESHPARAM1 in 500		    
			do
			#OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/MICDE_Data_2019/CarbonMonoxideData_old/co_mixing_with_eig_appended_mashParam_${MESHPARAM3}_tcOrder${TREECODEORDER}_tcTheta_${THETA}.csv"
			#OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/MICDE_Data_2019/CarbonMonoxideData/mashParam_${MESHPARAM3}_tcOrder${TREECODEORDER}_tcTheta_${THETA}.csv"
			
			
			OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/gaugeShiftTests/CO_asymmetric_ratioTol2e-2_gaugeShift${GAUGESHIFT}_LW5_${MESHPARAM1}.csv"
			#OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/krasnyMeshTests/Be_testing/Ox_T200_mixingHistory${MIXINGHISTORY}_mixingParam${MIXINGPARAMETER}_order${CELLORDER}_${BASE}_${MESHPARAM1}_${MESHPARAM2}_${MESHPARAM3}.csv"
			python -u testComputeSpectrum.py 	$DOMAIN $NORBITALS $TARGETENERGYEIGENVALUE $MINDEPTH $MAXDEPTH $ADDITIONALDEPTHATATOMS $CELLORDER $SINGSUBT \
																		$SMOOTHINGEPS $GAUSSIANALPHA $GAUGESHIFT $MESHTYPE $MESHPARAM1 $MESHPARAM2 $INTERSCFTOLERANCE $INTRASCFTOLERANCE \
																		$OUTPUTFILE $INPUTFILE $VTKFILEDIR $GRADIENTFREE $SYMMETRICITERATION $MIXING $MIXINGPARAMETER $MIXINGHISTORY \
																		$GPUPRESENT $TREECODE $TREECODEORDER $THETA $MAXPARNODE $BATCHSIZE $MESHPARAM3 $MESHPARAM4 $BASE $RESTART $SAVEDMESH
			done   
		done
	done   
	
done
done
done
done 
done
