#!/bin/bash
cd /home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/CC_tests



DOMAIN=5
MAXDEPTH=20
MINDEPTH=3
SINGSUBT=1
SMOOTHINGN=0
SMOOTHINGEPS=0
INTRASCFTOLERANCE=1e-3
INTERSCFTOLERANCE=1e-5
INPUTFILE='../src/utilities/molecularConfigurations/dummyAtomAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/noAtomsAuxiliary.csv'
OUTPUTFILE='/home/njvaughn/HartreeTests/GaussianSingularitySubtraction/GaussianDensity_alpha2_domain5/runComparison.csv'
GAUSSIANDENSITYALPHA=2
GAUSSIANSUBTRACTIONALPHA=1
MESHTYPE='LW5'	
ORDER=7


MESHPARAM=1500
python -u testGaussianSingularitySubtraction.py $DOMAIN $MINDEPTH $MAXDEPTH $ORDER $SINGSUBT \
	$SMOOTHINGN $SMOOTHINGEPS $MESHTYPE $MESHPARAM $INTERSCFTOLERANCE $INTRASCFTOLERANCE \
	$OUTPUTFILE $INPUTFILE $VTKFILEDIR $GAUSSIANDENSITYALPHA $GAUSSIANSUBTRACTIONALPHA
