#!/bin/bash


cd /home/njvaughn/TAGI/3D-GreenIterations/adaptiveMesh/src/Green-Iteration-Routines

DOMAIN=20
MINDEPTH=3
SINGSUBT=1

SRCDIR='/home/njvaughn/TAGI/3D-GreenIterations/adaptiveMesh/src/'
#INPUTFILE='utilities/molecularConfigurations/hydrogenMoleculeAuxiliary.csv'
#INPUTFILE='utilities/molecularConfigurations/berylliumAuxiliary.csv'
#INPUTFILE='utilities/molecularConfigurations/oxygenAtomAuxiliary.csv'
INPUTFILE='utilities/molecularConfigurations/carbonMonoxideAuxiliary.csv' 
#INPUTFILE='utilities/molecularConfigurations/benzeneAuxiliary.csv'

VTKFILEDIR='None'


GRADIENTFREE='True'
SYMMETRICITERATION='False'   
GPUPRESENT='False'
 
TREECODE='True'      
MAXPARNODE=4000
BATCHSIZE=4000   
 
 
GAUSSIANALPHA=1.0 
GAUGESHIFT=-0.5

MESHTYPE='ParentChildrenIntegral'
#MESHTYPE='LW5'
RESTART='False'	
#SAVEDMESH='Be_PCI_1e-3.npy' 
SAVEDMESH='CO_mesh.npy'
#SAVEDMESH='CO_3e-7.npy'
#SAVEDMESH='None'

ADDITIONALDEPTHATATOMS=0

MIXINGPARAMETER=0.5 
MIXINGHISTORY=10 
  
INTRASCFTOLERANCE=1e-6
INTERSCFTOLERANCE=1e-5
     
#MIXING='Anderson'    
SMOOTHINGEPS=0.0

MESHPARAM1=250
MESHPARAM2=0
MESHPARAM3=3e-6
MESHPARAM4=0   

SINGSUBT=1 
CELLORDER=5
BASE=1 
MAXDEPTH=20
GRADIENTFREE='True'    
TREECODEORDER=8
THETA=0.7
MIXING='Anderson'		     

OUTPUTFILE="/home/njvaughn/synchronizedDataFiles/eigOneTests/cpu_testing.csv"

#EPSLOW=-0.7
#EPSHIGH=-0.3
#NEPS=10
EPSLOW=$1
EPSHIGH=$1
NEPS=1
NMU=8
echo $EPSLOW
python -u testEigenvalueOne.py 	$DOMAIN $MINDEPTH $MAXDEPTH $ADDITIONALDEPTHATATOMS $CELLORDER $SINGSUBT \
															$SMOOTHINGEPS $GAUSSIANALPHA $GAUGESHIFT $MESHTYPE $MESHPARAM1 $MESHPARAM2 $INTERSCFTOLERANCE $INTRASCFTOLERANCE \
															$OUTPUTFILE $INPUTFILE $SRCDIR $VTKFILEDIR $GRADIENTFREE $SYMMETRICITERATION $MIXING $MIXINGPARAMETER $MIXINGHISTORY \
															$GPUPRESENT $TREECODE $TREECODEORDER $THETA $MAXPARNODE $BATCHSIZE $MESHPARAM3 $MESHPARAM4 $BASE $RESTART $SAVEDMESH \
															$EPSLOW $EPSHIGH $NEPS $NMU

													
