#!/bin/bash
DOMAIN=15
MINDEPTH=3
MAXDEPTH=20
SMOOTHINGN=0
SMOOTHINGEPS=0.0
INTRASCFTOLERANCE=1e-2
INTERSCFTOLERANCE=1e-5
SINGSUBT=1


#INPUTFILE='../src/utilities/molecularConfigurations/carbonMonoxideAuxiliary.csv'


INPUTFILE='../src/utilities/molecularConfigurations/oxygenAtomAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/carbonAtomAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/berylliumAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/lithiumAuxiliary.csv'
#INPUTFILE='../src/utilities/molecularConfigurations/hydrogenMoleculeAuxiliary.csv'


cd /home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/KohnShamTests


OUTPUTFILE='/home/njvaughn/OxygenResults/uniformRefinement_LW3_800_'

MESHTYPE='LW3'
MESHPARAM=800
ORDER=4

python testUniformRefinement.py $DOMAIN $MINDEPTH $MAXDEPTH $ORDER $SINGSUBT \
	$SMOOTHINGN $SMOOTHINGEPS $MESHTYPE $MESHPARAM $INTERSCFTOLERANCE $INTRASCFTOLERANCE \
	$OUTPUTFILE $INPUTFILE $VTKFILEDIR
