#!/bin/bash

cd /home/njvaughn/Greens-Functions-Iterative-Methods/3D-GreenIterations/adaptiveMesh/tests
python testBatchGreenIterations.py 8 4 20 0.05 1e-2 5e-5
#python testBatchGreenIterations.py 8 4 20 0.05 1e-4 5e-5
#python testBatchGreenIterations.py 8 4 20 0.05 2e-4 5e-5
#python testBatchGreenIterations.py 8 4 20 0.05 5e-4 5e-5
#python testBatchGreenIterations.py 8 4 11 0.07 0.02 5e-5
#python testBatchGreenIterations.py 8 4 12 0.07 0.02 5e-5
#python testBatchGreenIterations.py 8 4 5 0.07 0.02 5e-5
#python testBatchGreenIterations.py 8 4 6 0.07 0.02 5e-5
#python testBatchGreenIterations.py 8 4 7 0.07 0.02 5e-5
#python testBatchGreenIterations.py 8 4 8 0.07 0.02 5e-5
#python testBatchGreenIterations.py 8 4 9 0.07 0.02 5e-5
#python testBatchGreenIterations.py 8 4 10 0.07 0.02 5e-5
#python testBatchGreenIterations.py 8 4 11 0.07 0.02 5e-5
#python testBatchGreenIterations.py 8 4 12 0.07 0.02 5e-5

