#!/bin/sh
#PBS -N vaughn
#PBS -M njvaughn@umich.edu
#PBS -m a

#PBS -l nodes=1:gpus=1,mem=8gb,walltime=01:00:00
#PBS -j oe
#PBS -V

#PBS -A krasny_fluxg
#PBS -q fluxg
#PBS -l qos=flux

####  End PBS preamble

#  Show list of CPUs you ran on, if you're running under PBS
if [ -n "$PBS_NODEFILE" ]; then cat $PBS_NODEFILE; fi

#  Change to the directory you submitted from
if [ -n "$PBS_O_WORKDIR" ]; then cd $PBS_O_WORKDIR; fi

#  Put your job commands here:
cd /home/njvaughn/Documents/NumbaTesting/src
python add.py
